#!/bin/bash
ARGS="$@"
APP="${APP:-Demo2D}"
MAIN="org.clueminer.demo.${APP}"
jarfile="$(ls -t target/*jar-with-dependencies.jar | head -1)"
JAVA_XMX="${JAVA_XMX:-4096m}"
echo "using max heap: $JAVA_XMX"
if [[ -f "$jarfile" ]]; then
  java -jar $jarfile $ARGS
else
  path="target/lib"
  if [[ -d $path ]]; then
    CLASSPATH=$(find "." -name '*.jar' | xargs echo | tr ' ' ':')
    java -Xmx$JAVA_XMX -cp $CLASSPATH $MAIN $ARGS
  else
    mvn "-Dexec.args=-classpath %classpath -Xmx$JAVA_XMX $MAIN $ARGS" -Dexec.executable=java -Dexec.classpathScope=runtime org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
  fi
fi

